### ISSUE TITLE
Поменять название переменной и метода

### ISSUE THREAD

**Issue by pingvin1308** [IlyaEliseev/CsharpForBeginners#1]
https://github.com/IlyaEliseev/CsharpForBeginners/blob/fea663c9655d0e3f563e4e2cf8ea6c0f59f55ec2/Shop/Shop/Program.cs#L9

А возможно и класса.
Честно говоря сейчас кажется, что названия подобраны не очень удачно.
В целом да, это интерфейс взаимодействия с магазинов. Странно, что переменная называется shop, это ведь не магазин.
А еще странно, что метод который затем вызывается называется CreateShop();

В данном случае мы имеем дело с приложением, а если точнее с консольным приложением.
Это значит, что доменный язык данной инфраструктуры так и намекает, что нужно назвать классы и методы следующим образом.
Application, ShopApplication, CliApplication или ShopCliApplication - кажутся более подходящими. 
Причем Application в данном случае это просто абстрактное приложение, 
CliApplication - это консольное приложение, 
ShopApplication - это абстрактное приложение про магазин.
ShopCliApplication - это консольное приложение про магазин.

переменная в данном случае может быть: 
app - частое сокращение для Application. Конечно сокращения лучше не делать в коде, но иногда это вполне уместно. Это те ситауции, когда смысл переменной тебе понятен 100% и нет никакой возможности что то перепутать.
application - ну тут все понятно
shopApplication - тоже думаю все понятно :)

Дальше поговорим про метод. Что должен делать метод CreateShop? Очевидно создавать экземпляр магазина. А в твоем случае он должен был запускать приложение. 
Тут тоже есть парочка подходящих названий: Run(), Start(). И как видно, не приходится изобретать велосипеды :)

**Comment by IlyaEliseev** [comment]
Поправил
